name: olets.dev
version: 1.0.0
description: Source for olets.dev
main: index.js
scripts:
  build: eleventy
  watch: eleventy --watch
  serve: eleventy --serve
  start: eleventy --serve
  debug: DEBUG=* eleventy
  # build: pnpm clean && pnpm gulp build && pnpm dev:fonts
  # build:fonts: >-
  #   pnpm glyphhanger dist/*.html --subset=src/fonts/HeyAugust.woff2
  #   --formats=woff2 --output=dist --cssSelector=.font-serif
  # clean: pnpm gulp clean
  # dev: pnpm clean && pnpm dev:fonts && pnpm gulp dev
  # dev:fonts: cp src/fonts/HeyAugust.woff2 dist/HeyAugust-subset.woff2
keywords: []
author: Henry Bley-Vroman <olets@olets.dev>
license: SEE LICENSE IN LICENSE
devDependencies:
  '@11ty/eleventy': ^1.0.0
  '@11ty/eleventy-navigation': ^0.3.2
  '@11ty/eleventy-plugin-rss': ^1.1.2
  '@11ty/eleventy-plugin-syntaxhighlight': ^4.0.0
  '@types/markdown-it': ^12.2.3
  autoprefixer: ^10.4.2
  browser-sync: ^2.27.7
  del: ^6.0.0
  glyphhanger: ^5.0.0
  gulp: ^4.0.2
  gulp-htmlmin: ^5.0.1
  gulp-postcss: ^9.0.1
  gulp-twig: ^1.2.0
  luxon: ^2.3.0
  markdown-it: ^12.3.2
  markdown-it-anchor: ^8.4.1
  postcss: ^8.4.5
  tailwindcss: ^3.0.18
  yaml: ^1.10.2
repository:
  type: git
  url: git+https://github.com/olets/olets.dev.git
bugs:
  url: https://github.com/olets/olets.dev/issues
homepage: https://github.com/olets/olets.dev#readme
peerDependencies:
  '@types/markdown-it': ^12.2.3
