name: olets.dev
version: 1.0.0
description: Source for olets.dev
main: index.js
scripts:
  build: pnpm build:eleventy && pnpm build:tailwind && pnpm build:fonts
  build:eleventy: ELEVENTY_PRODUCTION=true eleventy
  build:tailwind: >-
    NODE_ENV=production pnpm tailwind -i css/index.css -c tailwind.config.js -o
    _site/css/index.css --minify
  watch: eleventy --watch
  dev: pnpm dev:eleventy & pnpm dev:tailwind
  debug: DEBUG=* eleventy
  dev:eleventy: eleventy --serve
  dev:tailwind: >-
    pnpm tailwindcss -i css/index.css -c tailwind.config.js -o
    _site/css/index.css --watch
  build:fonts: >-
    pnpm glyphhanger _site/*.html --subset=_site/fonts/HeyAugust.woff2
    --formats=woff2 --output=_site/fonts
keywords: []
author: Henry Bley-Vroman <olets@olets.dev>
license: SEE LICENSE IN LICENSE
devDependencies:
  '@11ty/eleventy': ^1.0.0
  '@11ty/eleventy-navigation': ^0.3.2
  '@11ty/eleventy-plugin-rss': ^1.1.2
  '@11ty/eleventy-plugin-syntaxhighlight': ^4.0.0
  '@tailwindcss/typography': ^0.5.1
  '@types/markdown-it': ^12.2.3
  autoprefixer: ^10.4.2
  browser-sync: ^2.27.7
  del: ^6.0.0
  eleventy-plugin-shiki-twoslash: ^1.0.44
  glyphhanger: ^5.0.0
  gulp: ^4.0.2
  gulp-htmlmin: ^5.0.1
  gulp-postcss: ^9.0.1
  gulp-twig: ^1.2.0
  luxon: ^2.3.0
  markdown-it: ^12.3.2
  markdown-it-anchor: ^8.4.1
  postcss: ^8.4.5
  tailwindcss: ^3.0.18
  yaml: ^1.10.2
repository:
  type: git
  url: git+https://github.com/olets/olets.dev.git
bugs:
  url: https://github.com/olets/olets.dev/issues
homepage: https://github.com/olets/olets.dev#readme
peerDependencies:
  '@types/markdown-it': ^12.2.3
